### ISSUE TITLE
Exit code tokenizer

### ISSUE THREAD

**Issue by taandreo** [taandreo/minishell#4]

**Comment by edu-bm7** [comment]
Added  the exit code to each tokenize function. Moving to extensively test the exit codes to check it correctness [commit d3b86d4](https://github.com/taandreo/minishell/commit/d3b86d4c0a53d8157d828ca6f9fd2777d5dbc761)

**Comment by edu-bm7** [comment]
Tokenizer now saves the exit code to flags->status, and it exit the program with this status [commit 11269b7](https://github.com/taandreo/minishell/commit/11269b70ccbca0c8c1cbcb72f1581a0e81cc3267). After the code evolves, we should use this status only to exit the program if something is wrong meaning `flags->status != SUCCESS`

**Comment by edu-bm7** [comment]
For now we are going to use `t_token_flags` to save the tokens exit codes. Closing this issue and marking as Done, if we change the behaviour of the program in the future we can reopen this issue
