### ISSUE TITLE
Tokenizer

### ISSUE THREAD

**Issue by taandreo** [taandreo/minishell#7]

**Comment by edu-bm7** [comment]
Tokenizer now needs the implementation of parenthesis `()` for priority and wildcards `*`

**Comment by edu-bm7** [comment]
In order to keep our workflow compatible with TDD, I'll first test the functionality of strings and quotes tokenization, then implement the parenthesis and wildcards functionality.

**Comment by edu-bm7** [comment]
Tokenizer now has everything done. Just a minor bug with the TOKEN_EXIT_CODE `$?` tokenization, but it'll be solved tomorrow. Now we need to write a lot of tests to ensure the correctness of our code.

**Comment by edu-bm7** [comment]
Tokenizer is now fully working, perfectly fine and consistently [7153906](https://github.com/taandreo/minishell/commit/7153906c42024355d6732170c19c768d18e2583d)
