### ISSUE TITLE
Parser Bonus (&& and ||)

### ISSUE THREAD

**Issue by taandreo** [taandreo/minishell#9]
## Bonus part

-  && and || with parenthesis for priorities.

**Comment by edu-bm7** [comment]
Need to make a new token for parenthesis`()` so the parser know when to prioritize `&&` and `||` instead of pipelines `|`.

**Comment by edu-bm7** [comment]
The part of tokenization of both AND, OR and `()` are done. Now its all about the parser

**Comment by edu-bm7** [comment]
The parser is correctly handling `()&&||`
